### ISSUE TITLE
Retina Image does not re-load after element has been destroyed

### ISSUE THREAD

**Issue by 2xAA** [wangbinyq/vue-retina#1]
I'm using vue-retina with with vue-router and after moving routes, then moving back the retina image in the previous route does not re-load as retina.

**Comment by wangbinyq** [comment]
which version do your use?
The latest version will retina image whenever it is loaded.

**Comment by 2xAA** [comment]
Yes, I was on 0.1.9 - fixed in 0.1.11. Thanks 😄
